require:
  - standard
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_gem:
  standard: config/ruby-3.2.yml
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.3

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/RedundantSelf:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true
